### ISSUE TITLE
Issue with create a new project - username for github

### ISSUE THREAD

**Issue by AkiraCaio** [artemnovichkov/swift-project-template#56]
frozen in this step 
![Captura de Tela 2020-05-05 às 00 52 11](https://user-images.githubusercontent.com/26613143/81033623-adb1a700-8e6a-11ea-8ac3-a9ecab8427df.png)

**Comment by artemnovichkov** [comment]
Hi, @AkiraCaio!Could you please check `carthage update` command in another project?

**Comment by AkiraCaio** [comment]
> Hi, @AkiraCaio!Could you please check `carthage update` command in another project?

Hello @artemnovichkov, the carthage work fines, my problem is that during the creation of the project in the step of informing my git user it is simply frozen in this step

**Comment by artemnovichkov** [comment]
I guess the issue is [here](https://github.com/artemnovichkov/swift-project-template/blob/2d6068b4b658143b06145ab4160244999d02ed0a/%7B%7B%20cookiecutter.name%20%7D%7D/bin/init.sh#L18). Fastfood is a tool for downloading and updating fastlane. And it tried to download sources fro private repo. It would be great to handle this case and ask users install fastlane or not.
